name: flutter_expanded_tile
description: An Expansion tile similar to the list tile supports leading widget,and programatic control with content expansion animation.
version: 0.4.0
homepage: https://github.com/micazi/flutter_expanded_tile

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">3.10.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
